### ISSUE TITLE
mismatch Action Name of the intent "tell_latest_tip"  

### ISSUE THREAD

**Issue by 01en** [actions-on-google/dialogflow-updates-nodejs#1]
The Action Name Intent:tell_latest_tip is different between index.js and DialogFlow. 
Beacause of this, I can't try the sample project and needed to modify Action:`tell_latest_tip` of DialogFlow Project to `tell.latest.tip`. 

Please check this 🙏  

- index.js (https://github.com/actions-on-google/dialogflow-updates-nodejs/blob/master/functions/index.js#L28)
```js
tell.latest.tip
```

- DialogFlow (https://github.com/actions-on-google/dialogflow-updates-nodejs/blob/master/AoG-Tips.zip)
```
tell_latest_tip
```

tell_latest_tip.json from unziped AoG-Tips.zip
```json
{
  "id": "90926160-1418-410b-81a8-3a2f481c9f9f",
  "name": "tell_latest_tip",
  "auto": true,
  "contexts": [],
  "responses": [
    {
      "resetContexts": false,
      "action": "tell_latest_tip",   <----- Here
      "affectedContexts": [],
      "parameters": [],
      "messages": [
        {
          "type": 0,
          "lang": "en",
          "speech": []
        }
      ],
      "defaultResponsePlatforms": {},
      "speech": []
    }
  ],
  "priority": 500000,
  "webhookUsed": true,
  "webhookForSlotFilling": false,
  "lastUpdate": 1515003380,
  "fallbackIntent": false,
  "events": []
}
```

**Comment by mInzamamMalik** [comment]
+1

**Comment by taycaldwell** [comment]
The .zip file included in the sample has been updated with the correct action name.

**Comment by 01en** [comment]
Thanks！ +1
