### ISSUE TITLE
 logged out of my test app

### ISSUE THREAD

**Issue by JeroenDePrest** [actions-on-google/dialogflow-updates-nodejs#11]
When I try the sample after running through the setup steps I get the following response: 

Alright. Here's the test version of my test app.
It looks like you've been logged out of my test app. To log back in, you'll need to ask to talk to them again.

What am I forgetting or what did I do wrong?

**Comment by taycaldwell** [comment]
Do you receive any error messages in the Error/Debug tabs of the Simulator that you can provide?

**Comment by JeroenDePrest** [comment]
I have no idea why it happend but it worked when I tried it again yesterday
