### ISSUE TITLE
Notifications on Google Assistant display

### ISSUE THREAD

**Issue by tony-topper** [actions-on-google/dialogflow-updates-nodejs#12]
I have this pushing notifications to my smartphone but it doesn't seem to support Google Assistant displays.   

Is this something that can be coded?   Or it it simply not supported at this time?

I noticed in the Device Settings it mentions notifications and they are enabled, so that makes me think this feature should be supported on the display.  I am testing on the Lenovo display.

**Comment by Fleker** [comment]
Notifications are not supported on smart displays.
