### ISSUE TITLE
Cancelling push notifications

### ISSUE THREAD

**Issue by tony-topper** [actions-on-google/dialogflow-updates-nodejs#13]
Is there a way to cancel a Google Assistant push notification after it's been sent?   

As IoT becomes more prevalent we could be notifying users via multiple platforms.   If they've interacted with a notification somewhere else, we need a way to cancel that notification on other platforms.

**Comment by vaibhavkumar049** [comment]
You can clear storage for user Token

**Comment by taycaldwell** [comment]
Hi @tony-topper,

As mentioned by @vaibhavkumar049, 
Upon a user interacting with a notification (i.e. triggering the intent), you can remove the unique identifier for that user from storage so notifications are no longer sent.
