### ISSUE TITLE
Push notifications are not sent 

### ISSUE THREAD

**Issue by santhosh-ktec** [actions-on-google/dialogflow-updates-nodejs#16]
When making POST request to `https://actions.googleapis.com/v2/conversations:send` its getting below 400 error 
**Body**
```
{
	"customPushMessage": {
		"target":{
			"userId": "XXXXXXXXXXXXXX",
			"intent": "save_sugar_test_result",
			 "locale": "en-US"
		},
		"userNotification": {
			"text": "Personal reminder"
		}
	},
	"isInSandbox": true
}
```
```
{
    "error": {
        "code": 400,
        "message": "Request contains an invalid argument.",
        "status": "INVALID_ARGUMENT"
    }
}
```

When I remove `userNotification `object its returning 200 ok. But notification is not triggered.
Guess `https://actions.googleapis.com/v2/conversations:send` endpoint was updated which needs to be updated in sample.  

Also it would be helpful if there is any links to documentation on the API for `https://actions.googleapis.com/v2/conversations:send` there is no clue of other params or endpoints available on that REST API.

**Comment by findzaatar** [comment]
You can find the parameters you'll need for post requests for push notifications in the [docs](https://developers.google.com/actions/assistant/updates/notifications#exchange_the_key_for_an_access_token_and_send_a_notification).

**Comment by santhosh-ktec** [comment]
For some reason it's throwing 400 INVALID_ARGUMENT error. The sample provided is not working,  even when the same repository code is deployed. 

The sample is broken which needs to be fixed

**Comment by findzaatar** [comment]
Just tested and the sample is working properly --  ensure all of the steps documented in the README are being followed. Ex: 
+ As mentioned in the Troubleshooting section of the README, if using iOS make sure you allow notifications for Assistant in Settings.  
+ Ensure you've enabled the Actions API, 
+ Visit `https://${REGION}-${PROJECT}.cloudfunctions.net/restoreTipsDB` in your browser, 
+ Turn on the push notifications and daily updates toggles in the Actions console
<img width="492" alt="Screen Shot 2019-06-17 at 10 45 47 AM" src="https://user-images.githubusercontent.com/11345614/59625027-22fa7900-90ed-11e9-86f4-1dda7cb09a0a.png">

+ After you've gone through this conversation flow then add a tip to the Firebase DB and after ~3 mins you will receive a push notification on your mobile device associated with your Assistant-enabled account. 


Similarly, you can view the sample's post request for push notifications via [here](https://github.com/actions-on-google/dialogflow-updates-nodejs/blob/master/functions/index.js#L193)

**Comment by santhosh-ktec** [comment]
Thanks @sarahdwyer it was working when tested from different account. The issue is its working only for the first time. The next time onwards` conv.arguments.get('UPDATES_USER_ID')` is received as null. 

Is there anyway to fix it?. For time being I included another condition to check value is null and show user that they already subscribed for push notifications. But i'm not sure its the correct fix. Also if I miss to save the value to DB at very first time when testing, I don't have option to get back the `userId`.
