### ISSUE TITLE
Mistake in the official document

### ISSUE THREAD

**Issue by 01en** [actions-on-google/dialogflow-updates-nodejs#2]
js sample code syntax is incorrect.

https://developers.google.com/actions/assistant/updates/daily#finalize_the_subscription
https://developers.google.com/actions/assistant/updates/notifications#finalize_the_subscription
```js
// incorrect 
appMap.set('finish.update.setup', function(app)) {
  if (app.isUpdateRegistered()) {
    app.tell("Ok, I'll start giving you daily updates.");
  } else {
    app.tell("Ok, I won't give you daily updates.");
  }
}

// correct 
appMap.set('finish.update.setup', function(app) {
  if (app.isUpdateRegistered()) {
    app.tell("Ok, I'll start giving you daily updates.");
  } else {
    app.tell("Ok, I won't give you daily updates.");
  }
})
```

also , Is correct both `appMap` and `actionMap`? I think `actionMap` is better.

Please check this 🙏 thanks.

**Comment by mInzamamMalik** [comment]
+1

**Comment by taycaldwell** [comment]
This issue has been resolved with version 2 of the Node.js client library.
