### ISSUE TITLE
Problem with latest firebase-tools

### ISSUE THREAD

**Issue by timgivois** [actions-on-google/dialogflow-updates-nodejs#4]
When using latest firebase-tools, I'm getting the following error:
```
Firebase config variables are not available. Please use the latest version of the Firebase CLI to deploy this function.
```

Solved installing `firebase-tools@3.16.0`. This [link](https://stackoverflow.com/questions/48531993/firebase-config-variables-are-not-available-error-with-deploying-functions) helped me, documentation should reflect one of the two workarounds (downgrading `firebase-tools` or updating to latest `firebase-admin` and `firebase-functions`).

**Comment by RedSpeeds** [comment]
Resolved by updating using npm update inside of the functions folder

**Comment by findzaatar** [comment]
@timgivois Please specify which exact version you had when you saw this error. 

Version 6.4.0 works without error messages. 

```
npm install firebase-tools@6.4.0 
```
