### ISSUE TITLE
Need to incorporate googleapis update for authorization.

### ISSUE THREAD

**Issue by funyapu** [actions-on-google/dialogflow-updates-nodejs#8]
https://github.com/actions-on-google/dialogflow-updates-nodejs/blob/b54c4d31647d46409ece33d947e514f5b0b8ea1f/functions/index.js#L210

Need to specifically call `google` module like below:

```
 const { google } = require('googleapis');
```

ref. https://github.com/google/google-api-nodejs-client/pull/943

**Comment by findzaatar** [comment]
Fixed and closing, thanks for reporting!
