### ISSUE TITLE
why Configure updates event is needed in setup_update intent

### ISSUE THREAD

**Issue by adambezecny** [actions-on-google/dialogflow-updates-nodejs#9]
hi,

why **Configure updates** event is actually needed in setup_update intent? I assume this event is called when intent actions.intent.CONFIGURE_UPDATES is triggered. On the other hand setup_intent is triggered via utterance 'Send daily' (as a result of updates opt-in via suggestion chip).

From AoG doc (https://developers.google.com/actions/assistant/updates/daily#actionsdk) it is nto quite clear for what purpose actions.intent.CONFIGURE_UPDATES is actually needed.  actionssdk example seems to be working fine without it. Can this be clarified?

thank you

**Comment by adambezecny** [comment]
please not this issue is interconnected with issue #5 (is actions.intent.CONFIGURE_UPDATES needed?) for **actions-on-google/actionssdk-updates-nodejs** repo

**Comment by taycaldwell** [comment]
Hi @adambezecny,

The *actions.intent.CONFIGURE_UPDATES* event is called when the Configure Updates [built-in intent](https://developers.google.com/actions/discovery/built-in-intents) is triggered.

So the setup_update intent fulfillment logic can either be triggered using the training phrase (provided by the suggestion chip), or by using a phrase to trigger the built-in intent.

The *actions.intent.CONFIGURE_UPDATES* event is not required. You can just trigger the intent via a training phrase if you'd like. It just provides a different way to trigger the same intent (using a built-in intent).

**Comment by adambezecny** [comment]
hi,

if I understand it correctly you mean it is possible to initiate daily update opt-in by invoking **actions.intent.CONFIGURE_UPDATES** in programmatic way (in contrast to 'standard' way when user's utterance is captured by intent which in turn calls **RegisterUpdate** in its fulfillment to initiate daily update setup).

Can you be more specific? Is there some example of how intent **actions.intent.CONFIGURE_UPDATES** can be triggered in programmatic way? I was not aware of such a possibility (always thought these built in intents are actually triggered by AoG itself, not from action code directly). thanks for clarification!

regards,

Adam
